FROM cm2network/steamcmd:latest

# https://www.cnblogs.com/shiraka/p/14004966.html#1%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85steamcmd
# https://steamcommunity.com/sharedfiles/filedetails/?l=german&id=360404397
